### ISSUE TITLE
Fix for Horribly Laggy UI

### ISSUE THREAD

**Issue by tsbockman** [CyanogenMod/android_device_motorola_clark#6]
The clark edition of SlimRom [recently merged a fix](https://github.com/SlimRoms/device_motorola_clark/commit/ea116d8b20989068c3735132c23e4859c0ae7413) for the awful UI lag that lots of people have been complaining about on XDA which affects CyanogenMod, too.

I manually installed the updated `init.qcom.power.sh` on my phone using TWRP, and it seems to work as advertised: it eliminates the lag without hurting battery life. I am currently running an otherwise unmodified CyanogenMod `13.0-20161102-NIGHTLY-clark` with Open GApps.

**Comment by byron8899** [comment]
Thanks tsbockman for an update on this.  I was using kernel aduitor to modify the cpu values, but it affects my battery life.  I'll be trying the sh script today today.

**Comment by damentz** [comment]
I tested this last night and this morning.  My only concern is that the go_hispeed_load property is set too high at 99.  Driving to breakfast this morning, my bluetooth was cutting out periodically, multiple times during the drive.  After reducing this value to 98, my bluetooth stopped dropping out.

Otherwise, my phone feels much more responsive and fluid.  Battery life is also excellent, identical to a previous custom configuration I was using with ondemand and qualcomm hotplugging for big cores.  No SODs or random restarts so far.

**Comment by tsbockman** [comment]
> My only concern is that the go_hispeed_load property is set too high at 99. Driving to breakfast this morning, my bluetooth was cutting out periodically, multiple times during the drive. After reducing this value to 98, my bluetooth stopped dropping out.

Yes, after looking up what that parameter is for and what others typically set it to, 99 seems really high. The highest value I see other people use is 95; I will try that and see how my battery does.

**Comment by damentz** [comment]
Ok, so I think I found a magic selection that works great for my use case.  I was getting fast battery drain while on the way to work (I take the train in Austin), while listening to podcasts.  I changed the interactive settings to the following, basically to reduce the over-eager increase in cpu frequencies:

Big Cores:
_Reduce minimum frequency to 384 (hotplugging disabled, helps with SOT and general idle battery life)_
interactive settings:
- fast_ramp_down = 1
- go_hispeed_load = 98
- io_is_busy = 0
- target_loads = '80 960000:80 1248000:95'

Small Cores:
interactive settings:
- fast_ramp_down = 1
- go_hispeed_load = 98
- io_is_busy = 1
- target_loads = '80 460800:80 960000:95'

@tsbockman what did you find with your testing?  I really like that the phone is much more stable and doesn't crash / random reboot with qualcomm hotplugging disabled, but I feel like the settings should be adjusted to prevent the big cores from activating at too high a frequency (and thus voltage), when the phone isn't being used heavily.  Also, I think setting 'fast_ramp_down = 0' on small cores (which is currently set), won't be an issue.

**Comment by tsbockman** [comment]
I am now testing the November 12th build, which has a few power management-related updates ([init: tune core_ctl per stock](https://github.com/CyanogenMod/android_device_motorola_clark/commit/b2b58966279e8c7b10a290afb7591c0b12f40259), [clark: allow hotplugging both big cores while the screen is off](https://github.com/CyanogenMod/android_device_motorola_clark/commit/639e74aeafb1424a0614e0f4237b54fc6b69abc1), and [power: set min_cpus after max_cpus](https://github.com/CyanogenMod/android_device_motorola_clark/commit/aafcf829397d5272ddd08b6a8605d4187f77c604)).

So far it seems good; it feels very similar to the SlimRom config. If anything, it's a little less smooth (but still good), with slightly better battery life.

If that continues, I will close this issue in a few days unless someone objects.

**Comment by damentz** [comment]
The stock Motorola configuration is stable, my phone doesn't randomly reboot or have any sleep of deaths.  However, it feels as slow and laggy like OEM stock.  What I like about the configuration that spawned this issue is that hotplugging is completely disabled, and with a few more tweaks, it uses just as much battery as the OEM configuration, but without the lag spikes.

A good example is installing updates through the play store while scrolling a web page.  For some reason with the stock configuration, it makes it horribly unusable.  There's also situations where I'm trying to pull down notifications to tap on something, and I have to wait 2 seconds before it responds and follows my finger - very irritating.

@tsbockman Maybe we can come up with a compromise between OEM configuration and what Slim found out?  I still vouch for the adjustments to the configuration just one post before.

**Comment by damentz** [comment]
Another change I'm testing is **setting /proc/sys/kernel/sched_upmigrate_min_nice to 0** (previously set to 9).  This setting prevents processes and threads that are nicer than this setting from being scheduled on the big cores.  So far so good - this should prevent more types of background tasks from running on the big cores, especially when the screen is off allowing the big cores to go into deep sleep.

Basically, the goal is that when the screen is off, even without hotplugging, the big cores go unused and can enter deep sleep, emulating hotplugging but without the cost of the laggy UI and responsiveness you get with with the stock configuration.

Also, I saw on the LG G4 kernel, 5 cpufreq commits were cherry-picked to improve hotplugging and general cpufreq performance, not sure how much it will affect clark, but both clark and h815 (lg g4) use the same SoC:

https://github.com/CyanogenMod/android_kernel_lge_msm8992/commit/aecb7164bd34b0e978bb98b7eab3a9bb306c883a
https://github.com/CyanogenMod/android_kernel_lge_msm8992/commit/a00f0abd3d89b5775aeb7e407d63c52f3a81f313
https://github.com/CyanogenMod/android_kernel_lge_msm8992/commit/ff75c39ea93f9c9beff4d4fd63e81adac1d6996c
https://github.com/CyanogenMod/android_kernel_lge_msm8992/commit/4f1342c35b91b8cc14f8b6bb5aeafe987bc78141
https://github.com/CyanogenMod/android_kernel_lge_msm8992/commit/4e60eaf1cdd2c6648de3e382ef614f1b2ec72a72

**Comment by byron8899** [comment]
I am experiencing a similar issue as what damentz mention.  For my situation, sometimes, I experience lockscreen lag after I turn on the screen.  I had to wait a few seconds to get UI back to normal.  In order to fix the issue,  I have to reset the system UI and then later on its back to normal.   I'll probably try the change as well and see what happens.

**Comment by tsbockman** [comment]
I am still having issues with lag and instability with the new stock config after the phone has been on for a while, just not as severe as before. So I will keep this open and continue experimenting as @damentz suggested.

**Comment by damentz** [comment]
So, I've been using the modified **init.qcom.power.sh** file and I'm achieving zero battery drain when the phone is not in use.  I think that hotplugging probably only really helps a lot with screen-on-time where you're just scrolling through an app / web page.

![moto-x-pure-2015-battery-life](https://cloud.githubusercontent.com/assets/284931/21075559/f343c608-beda-11e6-9fc8-0338132efd11.png)

Here is a patch to the commit @tsbockman linked to in his first post to get the configuration I've been testing the last few weeks (with CM 14.1 as well).

https://gist.github.com/damentz/df8f782b8c1b19092e2dc148d18ee773

Since battery drain has been fixed since **cm-14.1-20161210-NIGHTLY-clark.zip**, I _highly_ recommend we use the slim rom configuration with the patch I have attached, as it fixes the inevitable lag and keeps performance consistent and predictable throughout the entire uptime of the phone.

**Comment by damentz** [comment]
Ah, and just pointing out, it looks like the Slim rom configuration came from the Nexus 5X (which also runs the Snapdragon 808):

https://android.googlesource.com/device/lge/bullhead/+/master

If you check the `init.bullhead.power.sh` file, you'll find that they're mostly identical.  Perhaps if we're not sure how to move forward, we can take bits from Google's configuration and replace Motorola's?  At least we know that Google has been fixing the changes incrementally per the log of this configuration file:

[Log - master - device/lge/bullhead - Git at Google - init.bullhead.power.sh](https://android.googlesource.com/device/lge/bullhead/+log/master/init.bullhead.power.sh)

**Comment by byron8899** [comment]
Seems like the script worked great.   Thanks for sharing.  I'm not very much savy on the kernels, but I'll still continue to do testing on this.  It's seems here is pretty quiet compare to the xda forums.

**Comment by tsbockman** [comment]
> I highly recommend we use the slim rom configuration with the patch I have attached, as it fixes the inevitable lag and keeps performance consistent and predictable throughout the entire uptime of the phone.

I'm running `13.0-20161121-NIGHTLY-clark`, and I've been using a configuration very similar to yours. It's (mostly) been working very well for me, too. Certainly, it is better than the stock config.

> It's seems here is pretty quiet compare to the xda forums.

Yeah, I'm not sure if this was the best place to report this. I did post it on the forums, too, though, and one of the maintainers responded. So, they are aware of the issue.

I wonder if they've seen your patch though, @damentz ? Perhaps you should post it on the forum, too?
